"""Added role column to User

Revision ID: 441532138f5d
Revises: c114dd7f4397
Create Date: 2025-02-11 20:16:38.149758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441532138f5d'
down_revision: Union[str, None] = 'c114dd7f4397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_service_users_email', table_name='users')
    op.drop_index('ix_user_service_users_id', table_name='users')
    op.drop_index('ix_user_service_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_user_service_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_user_service_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_user_service_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
