"""Recreated initial migration

Revision ID: c114dd7f4397
Revises: 
Create Date: 2025-02-10 20:28:39.346657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c114dd7f4397'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='user_service'
    )
    op.create_index(op.f('ix_user_service_users_email'), 'users', ['email'], unique=True, schema='user_service')
    op.create_index(op.f('ix_user_service_users_id'), 'users', ['id'], unique=False, schema='user_service')
    op.create_index(op.f('ix_user_service_users_username'), 'users', ['username'], unique=True, schema='user_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_service_users_username'), table_name='users', schema='user_service')
    op.drop_index(op.f('ix_user_service_users_id'), table_name='users', schema='user_service')
    op.drop_index(op.f('ix_user_service_users_email'), table_name='users', schema='user_service')
    op.drop_table('users', schema='user_service')
    # ### end Alembic commands ###
