# =============================
# 📦 docker-compose.yml
# =============================

services:
  db_service:
    build:
      context: .
      dockerfile: db_service/Dockerfile
    env_file:
      - ./db_service/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

  user_service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    env_file:
      - ./user_service/.env
    ports:
      - "8002:8002"
    depends_on:
      - db_service

  orders_service:
    build:
      context: .
      dockerfile: orders_service/Dockerfile
    env_file:
      - ./orders_service/.env
    ports:
      - "8003:8003"
    depends_on:
      - db_service

  admin_service:
    build:
      context: .
      dockerfile: admin_service/Dockerfile
    ports:
      - "8004:8004"
    depends_on:
      - db_service
      - orders_service

  postgres_db:
    image: postgres:14
    env_file:
      - .env.postgres
    ports:
      - "5433:5432"  # 5433 наружу, 5432 внутри
    volumes:
      - postgres_data:/var/lib/postgresql/data

  envoy:
    image: envoyproxy/envoy:v1.26-latest
    ports:
      - "8080:8080"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - opa
      - user_service
      - orders_service
      - admin_service

  opa:
    image: openpolicyagent/opa:0.57.0
    platform: linux/amd64
    command: ["run", "--server", "--log-level", "debug", "/policies/policy.rego"]
    volumes:
      - ./envoy/policies:/policies
    ports:
      - "8181:8181"
volumes:
  postgres_data:
