"""Initial DB

Revision ID: a038fbf1fb74
Revises: 
Create Date: 2025-02-19 20:18:15.373788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a038fbf1fb74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='user_service'
    )
    op.create_index(op.f('ix_user_service_users_id'), 'users', ['id'], unique=False, schema='user_service')
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_service.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='orders_service'
    )
    op.create_index(op.f('ix_orders_service_orders_id'), 'orders', ['id'], unique=False, schema='orders_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_service_orders_id'), table_name='orders', schema='orders_service')
    op.drop_table('orders', schema='orders_service')
    op.drop_index(op.f('ix_user_service_users_id'), table_name='users', schema='user_service')
    op.drop_table('users', schema='user_service')
    # ### end Alembic commands ###
